/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright 1997-2002, All rights reserved
*         Risoe National Laboratory, Roskilde, Denmark
*         Institut Laue Langevin, Grenoble, France
*
* Component: Distrib2McStas_window
*
* %I
* Written by: 
* Date: 
* Origin: 
*
* Neutron guide.
*
* %D
* Description
*
* Example: Distrib2McStas_window(...)
*
* %VALIDATION
*
* %BUGS
*
* %P
* INPUT PARAMETERS:
*
* file_d1: [str]    File with current distribution in E
* file_d2: [str]    File with current distribution in E, x, y
* file_d3: [str]    File with current distribution in E, x, y, mu
* file_d4: [str]    File with current distribution in E, x, y, mu, phi
*
* %D
* Example values:
*
* %E
*******************************************************************************/

DEFINE COMPONENT Monitor_tracks
DEFINITION PARAMETERS ()
SETTING PARAMETERS (string pt="n", string filename="", xwidth=0.0, yheight=0.0)
OUTPUT PARAMETERS (outfile, I, p2, N)
/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */ 

SHARE
%{
	#include "mcpl.h"
%}

DECLARE
%{
	mcpl_outfile_t outfile;
	double I, p2;
	int N;
	mcpl_particle_t* part;
%}

INITIALIZE
%{  
	if(strlen(filename) == 0) strcat(strcpy(filename, NAME_CURRENT_COMP), "_tracks");
	outfile = mcpl_create_outfile(filename);
	mcpl_hdr_set_srcname(outfile,"McStas Guide_tracks");
	mcpl_enable_universal_pdgcode(outfile, pt2pdg(pt[0]));

	part = mcpl_get_empty_particle(outfile);

	I = p2 = N = 0;
%}

TRACE
%{
	if(-xwidth/2<x && x<xwidth/2 && -yheight/2<y && y<yheight/2){
		double v2 = (vx*vx + vy*vy + vz*vz);
		double E = 1e-9 * VS2E * v2;
		double v = sqrt(v2);
		part->ekin = E;
		part->position[0] = x*100.0; part->position[1] = y*100.0; part->position[2] = z*100.0;
		part->direction[0] = vx/v; part->direction[1] = vy/v; part->direction[2] = vz/v;
		part->weight = p;
		mcpl_add_particle(outfile, part);
	
		I += p;
		p2 += p*p;
		N++;
	
		SCATTER;
	}
%}

SAVE
%{
	printf("Monitor_tracks %s: I err N %lf %lf %d\n", NAME_CURRENT_COMP, I, sqrt(p2), N);
%}

FINALLY
%{
	mcpl_closeandgzip_outfile(outfile);
%}

MCDISPLAY
%{
	multiline(5,
    	-1.0, -1.0, 0.0,
    	 1.0, -1.0, 0.0,
    	 1.0,  1.0, 0.0,
    	-1.0,  1.0, 0.0,
    	-1.0, -1.0, 0.0);
%}

END
