name: kdsource

on:
    - push
    - pull_request

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: "Ubuntu_Latest_py310",
            os: ubuntu-latest,
            python-version: "3.10",
          }
          - {
            name: "MacOS_Latest_py313",
            os: macos-latest,
            python-version: "3.13",
          }

    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'true'

      - name: Install libxml2 + cmake (ubuntu)
        if: startsWith(matrix.config.name, 'Ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install cmake libxml2

      - name: Set up Python ${{ matrix.config.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.python-version}}

      - name: Install libxml2 + cmake (MacOS)
        if: startsWith(matrix.config.name, 'MacOS')
        run: |
          brew update
          brew install cmake libxml2

      - name: pip install + basic test
        run: |
          pip install .
          kdsource-config -s
          kdsource-resample -h
          python3 -c "import kdsource"
