name: kdsource

on:
    - push
    - pull_request

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
            name: "Ubuntu_Latest_py310",
            os: ubuntu-latest,
            python-version: "3.10",
          }
          - {
            name: "MacOS_Latest_py313",
            os: macos-latest,
            python-version: "3.13",
          }
          - {
            name: "Windows_Latest_py312",
            os: windows-latest,
            python-version: "3.12",
          }

    steps:

      - name: checkout
        uses: actions/checkout@v6.0.2

      - name: Set up Python ${{ matrix.config.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.config.python-version}}

      #Verify that MCPL works:
      - run: pip install mcpl
      - run: mcpl-config -s
      - run: python3 -c "import mcpl"

      #Now proceed to KDSource:
      - run: pip install .
      - run: kdsource-config -s
      - run: kdsource-resample -h
      - run: python3 -c "import kdsource"
      - run: kdsource-test
