name: pypi

on:
  push:
  pull_request:

jobs:
  preparations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          path: src
          #Workaround for https://github.com/actions/checkout/issues/1467:
          ref: ${{ github.ref }}
          fetch-tags: true

      - name: Setup python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.13'

      #A few tests before we launch all the platform jobs (todo: add more):
      - name: pylint with ruff
        run: pip install ruff && ruff check src/python/kdsource/*.py src/python/kdsource/*.py.in

      - name: Check if dryrun
        id: dryrun_check
        shell: bash
        run: |
          # Dryryn unless event has ref like refs/tags/v1.2.4 where the last
          # digit is even. Also, the tag must match the contents of the VERSION file.
          set -eux
          STATUS=1
          VERSIONSTR=$(cat ./src/VERSION)
          if [[ "${GITHUB_REF:-}" =~ ^refs/tags/v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            version="${BASH_REMATCH[0]#refs/tags/}"
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            patch="${BASH_REMATCH[3]}"
            bare_version="${major}.${minor}.${patch}"
            if (( patch % 2 == 0 )) && [[ "${bare_version}" == "${VERSIONSTR}" ]]; then
              STATUS=0
            fi
          fi
          echo "Dryrun: ${STATUS}"
          echo "status=${STATUS}" >> $GITHUB_OUTPUT

      - name: Determine version number
        id: version-number
        env:
          IS_DRYRUN: ${{ steps.dryrun_check.outputs.status }}
        run: |
          set -eux
          VERSIONSTR=$(cat ./src/VERSION)
          echo "Extracted version str: '${VERSIONSTR}'"
          echo "version_number=$VERSIONSTR" >> $GITHUB_OUTPUT

    outputs:
      kdsourceversion: ${{ steps.version-number.outputs.version_number }}
      dryrun: ${{ steps.dryrun_check.outputs.status }}
      # macos-15-intel is an intel runner, macos-14 is apple silicon. We
      # deliberately do not include windows arm at the moment (kdepy dep was
      # missing for one thing).
      platforms: '[ "ubuntu-latest", "ubuntu-24.04-arm", "macos-14", "macos-15-intel", "windows-latest" ]'

  basic_functionality_test:
    #Very basic testing only, we might have decided to publish a release even
    #with some tests showing spurious failures or similar. However, we always
    #tell users that "kdsource-test" can be used to test that everything works,
    #so at least that should always work.
    needs: [ preparations ]
    strategy:
      matrix:
        os: ${{ fromJson(needs.preparations.outputs.platforms) }}
    name: ${{ matrix.os }} / test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          path: src

      - name: Setup python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: '3.12'

      - name: Pip install sources
        run: pip install "./src"

      - name: kdsource-test
        run: kdsource-test

      - name: import kdsource
        run: python -c "import kdsource"

      - name: import kdsource.api
        run: python -c "import kdsource.api"

      - name: import kdsource.test
        run: python -c "import kdsource.test"

  build_sdists:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: preparations
    env:
      SDIST_SUFFIX: "-${{ needs.preparations.outputs.kdsourceversion }}.tar.gz"

    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - name: build kdsource sdist
        run: pipx run build --sdist .

      - run: ls -l ./dist/

      - name: register sdist
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: sdist-kdsource
          path: ./dist/kdsource${{ env.SDIST_SUFFIX }}
          if-no-files-found: error

    outputs:
      sdistname_kdsource: kdsource${{ env.SDIST_SUFFIX }}

  build_binary_wheels:
    #Based on
    #https://github.com/pypa/cibuildwheel/blob/main/examples/github-minimal.yml,
    #where we should check if something needs updating once in a while
    #(especially with respect to the hardcoded matrix.os list.
    #NOTE: Not building windows arm64 wheels, since anyway kdepy does not have them.
    needs: [ preparations, build_sdists ]
    strategy:
      matrix:
        os: ${{ fromJson(needs.preparations.outputs.platforms) }}
    name: ${{ matrix.os }} / kdsource binary wheels
    runs-on: ${{ matrix.os }}

    env:
      SDIST_PATH: "./sdist/${{ needs.build_sdists.outputs.sdistname_kdsource }}"

    steps:
      - name: download kdsource sdist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: sdist-kdsource
          path: ./sdist

      - name: Look in sdist dir (unix)
        if: runner.os != 'Windows'
        run: ls -l "${SDIST_PATH}"

      - name: Verify presence of sdist (unix)
        if: runner.os != 'Windows'
        run: test -f "${SDIST_PATH}"

      #Avoid auditwheel issues related to libmcpl.so (it will be found and
      #loaded at runtime, but auditwheel can not know that).
      - name: Prevent libmcpl.so in kdsource wheel (Linux)
        if: runner.os == 'Linux'
        run: echo 'CIBW_REPAIR_WHEEL_COMMAND_LINUX=auditwheel repair -w {dest_dir} {wheel} --exclude "libmcpl*"' >> $GITHUB_ENV

      - name: Prevent libmcpl.so in kdsource wheel (MacOS)
        if: runner.os == 'macOS'
        #NOTE: --ignore-missing-dependencies is not a great solution! But at least we have code below testing the wheels!
        run: echo 'CIBW_REPAIR_WHEEL_COMMAND_MACOS=delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel} --exclude libmcpl --ignore-missing-dependencies' >> $GITHUB_ENV

      # Run cibuildwheel. Both in default mode, and with additional steps for
      # manylinux2014 wheels.
      #
      - name: cibuildwheel
        uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084
        env:
          #no 32bit windows wheels:
          CIBW_ARCHS_WINDOWS: "auto64"
        with:
          package-dir: ${{ env.SDIST_PATH }}
          output-dir: wheelhouse

      - name: cibuildwheel manylinux2014
        uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084
        if: runner.os == 'Linux'
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
        with:
          package-dir: ${{ env.SDIST_PATH }}
          output-dir: wheelhouse

      - name: list wheelhouse (unix)
        if: runner.os != 'Windows'
        run: ls -l ./wheelhouse/

      - name: list wheelhouse (windows)
        if: runner.os == 'Windows'
        run: dir wheelhouse

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: kdsource-binary-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/kdsource-*.whl
          if-no-files-found: error

  collect_output:
    name: Collect all output
    needs: [ preparations, build_sdists, build_binary_wheels ]
    runs-on: ubuntu-latest
    steps:
      # sdist:
      - name: download kdsource sdist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: sdist-kdsource
          path: ./dist

      # binary wheels (merge-multiple: true since produced in several jobs):
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          pattern: "kdsource-binary-wheels-*"
          merge-multiple: true
          path: ./dist

      # Verify:
      - name: List files
        run: find ./dist

      - name: Verify presence of expected wheel files
        shell: python
        run: |
          import pathlib
          versionstr = '${{ needs.preparations.outputs.kdsourceversion }}'
          def expected_keys():
              keys = [
                  "macosx_10_9_x86_64",
                  "macosx_11_0_arm64",
                  "win_amd64",
                  "musllinux_1_2_x86_64",
                  "musllinux_1_2_aarch64",
                  "manylinux_2_26_aarch64.manylinux_2_28_aarch64",
                  "manylinux_2_26_x86_64.manylinux_2_28_x86_64",
                  "manylinux2014_aarch64.manylinux_2_17_aarch64",
                  "manylinux2014_x86_64.manylinux_2_17_x86_64",
              ]
              return keys
          def testpkg():
              print(f"==> Investigating kdsource")
              pdir = pathlib.Path(f'./dist').absolute()
              prefix = f'kdsource-{versionstr}-py3-none-'
              expected_files = set([ f'{prefix}{key}.whl' for key in expected_keys() ])
              expected_files.add(f'kdsource-{versionstr}.tar.gz')
              actual_files = set(f.name for f in pdir.iterdir())
              errmsgs = []
              if expected_files - actual_files:
                  errmsgs.append('Missing files: %s'%sorted(expected_files - actual_files))
              if actual_files - expected_files :
                  errmsgs.append('Unexpected files: %s'%sorted(actual_files - expected_files))
              if errmsgs:
                  for e in errmsgs:
                      print(f"ERROR kdsource: {e}")
                  return False
              print("Found exactly the expected files:")
              for f in sorted(expected_files):
                  print(f'  {f}')
              return True
          if not testpkg():
              raise SystemExit("Errors detected")

      - name: List files
        run: |
          find ./dist

      - name: Combine in final dir
        run: |
          mkdir ./dist_final
          cp ./dist/kdsource-*.whl ./dist_final
          cp ./dist/kdsource-*.tar.gz ./dist_final

      - name: List files
        run: find ./dist_final

      - name: Package artifacts
        run: tar cvzf final.tar.gz ./dist_final

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: final
          path: ./dist_final
          if-no-files-found: error

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: final-tarball
          path: final.tar.gz
          if-no-files-found: error

  test_wheels:
    needs: [ preparations, collect_output ]
    strategy:
      matrix:
        os: ${{ fromJson(needs.preparations.outputs.platforms) }}
    name: "${{ matrix.os }} / test wheels"
    runs-on: ${{ matrix.os }}
    steps:

      - name: download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: final
          path: ./dist_final

      - name: Setup python
        uses: actions/setup-python@4f41a90a1f38628c7ccc608d05fbafe701bc20ae
        with:
          python-version: '3.12'

      - name: Analyse wheel files
        shell: python
        run: |
          import pathlib
          import os.path
          from zipfile import ZipFile
          wheel_dir = pathlib.Path('.').joinpath('dist_final')
          errors = [False]
          def zip_content( p ):
              with ZipFile(p, 'r') as fh:
                  return fh.namelist()
          def validate_wheel( wheelfile, exceptions = None ):
              assert wheelfile.is_file()
              for fn in zip_content(wheelfile):
                  bnl = os.path.basename(fn).lower()
                  if any(bnl.endswith(e) for e in ('.dll','.dylib','.so','.a','.o','.exe')):
                      if exceptions and bnl in exceptions:
                          print(f"Found allowed binary in {wheelfile.name}: {fn}")
                      else:
                          errors[0] = True
                          print(f"Forbidden binary found in {wheelfile.name}: {fn}")
              return not errors
          def val( globpattern, exceptions = None ):
              wfs = sorted(wheel_dir.rglob(globpattern))
              assert wfs
              for f in wfs:
                  validate_wheel(f,exceptions)
          val( 'kdsource-*.whl',
               ['libkdsource.so','libkdsource.dylib','kdsource.lib','kdsource.dll'] )
          if errors[0]:
              raise SystemExit('Errors detected')

      - name: Pip install wheels
        env:
          PIP_FIND_LINKS: ./dist_final
        run: pip install "kdsource==${{ needs.preparations.outputs.kdsourceversion }}"

      - run: kdsource-config -s
      - run: kdsource-resample --help
      - run: kdsource-test

  publish_to_pypi:
    name: Publish to pypi
    needs: [ preparations, collect_output, test_wheels, basic_functionality_test ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:

      - name: download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: final
          path: ./dist_final

      - name: List files
        run: ls -l ./dist_final

      - name: Upload distribution to PyPI (if not dryrun)
        if: needs.preparations.outputs.dryrun == '0'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          packages-dir: ./dist_final
          verbose: true
